language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g codecov
install:
  - npm install
script:
  - npm test
  - mocha -r ts-node/register test/**/*.spec.ts --exit && codecov
  - codecov
after_success:
  - codecov